name: Windows system test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Systeminfo
      run: systeminfo
    - name: Hello World
      run: echo Hello World!
    - name: whoami
      run: ((Get-WMIObject -class Win32_ComputerSystem | Select-Object -ExpandProperty username)) 
    - name: Msinfo32
      run: ./msinfo32.ps1
    - name: Run batch now
      run: ./windows-system-test.ps1
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Test to upload
        path: \%userprofile%\Desktop\welp.txt
